/**
 * alarm-sound — the in-app noise layer that makes the gate real.
 *
 * The iOS AlarmKit system alarm has a mandatory "Dismiss" button we cannot
 * remove; tapping it silences the *system* alarm and launches the app. That
 * means the system alarm can only be treated as a WAKE. The actual,
 * un-silenceable alarm experience lives HERE, inside the app, behind the
 * challenge gate:
 *
 *   - startAlarmSound() begins a loud, looping sound + repeating haptics.
 *   - The ONLY authorised call site for stopAlarmSound() is the challenge
 *     success path (alarm-store.stopAlarm → ActiveAlarmOverlay.handleComplete).
 *   - Configured to play through the silent switch and keep going in the
 *     background (UIBackgroundModes: ["audio"]) so the user can't escape by
 *     flipping mute or backgrounding the app.
 *
 * Drop a looping alarm sound at assets/sounds/alarm.wav (a placeholder tone is
 * generated by default — replace it with whatever you want).
 */

import { createAudioPlayer, setAudioModeAsync, type AudioPlayer } from 'expo-audio';
import * as ExpoHaptics from 'expo-haptics';

const ALARM_SOURCE = require('../../assets/sounds/alarm.wav');

let player: AudioPlayer | null = null;
let hapticTimer: ReturnType<typeof setInterval> | null = null;

/**
 * Start the in-app alarm sound + haptics. Idempotent: calling it while already
 * playing is a no-op, so foreground re-assertions are safe.
 */
export async function startAlarmSound(): Promise<void> {
  if (player) return; // already ringing

  try {
    await setAudioModeAsync({
      playsInSilentMode: true,
      shouldPlayInBackground: true,
      interruptionMode: 'doNotMix',
    });
  } catch {
    // Audio session config best-effort; still try to play.
  }

  try {
    player = createAudioPlayer(ALARM_SOURCE);
    player.loop = true;
    player.volume = 1.0;
    player.play();
  } catch {
    player = null;
  }

  // Relentless haptics alongside the sound.
  if (!hapticTimer) {
    hapticTimer = setInterval(() => {
      ExpoHaptics.notificationAsync(
        ExpoHaptics.NotificationFeedbackType.Warning,
      ).catch(() => {});
    }, 1500);
  }
}

/**
 * Stop the in-app alarm sound + haptics and release resources.
 * Only call this on challenge success (via alarm-store.stopAlarm).
 */
export function stopAlarmSound(): void {
  if (hapticTimer) {
    clearInterval(hapticTimer);
    hapticTimer = null;
  }
  if (player) {
    try {
      player.pause();
      player.remove();
    } catch {}
    player = null;
  }
}
